Release for DSM7.0

diff --git a/SynoInstall b/SynoInstall
--- a/SynoInstall
+++ b/SynoInstall
@@ -1,10 +1,18 @@
 #!/bin/bash
-# Copyright (c) 2000-2016 Synology Inc. All rights reserved.
-
-. $(dirname `readlink -f "$0"`)/include/init
+# Copyright (c) 2000-2020 Synology Inc. All rights reserved.
 
 LANG=""
 LC_ALL=""
+
+. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/include/init
+
+CFLAGS=""
+LDFLAGS=""
+
+Source include/install
+Source include/util
+
+CheckPermission
 
 Usage() {
 	cat << EOF
@@ -20,30 +28,16 @@ Options
 		Specify target platform.
 	-d, --with-debug
 		Install binaries with debug symbols.
+	--parallel N
+		Parallel install projects with N processes
 	-h, --help
 		This help message.
 EOF
 }
 
-Source include/install
-CheckPermission
-
-ARGS=`getopt -u -l $DefaultLongArgs,enable-apt,single $DefaultArgs $@`
-
-if [ $? -ne 0 ]; then
-	echo "You gave me option(s) that I do not know."
-	Usage
-	exit 1
-fi
-set -- $ARGS
-
-
 ParsePkgInstallArgs() {
 while [ -n "$1" ]; do
 	case "$1" in
-	"--enable-apt")
-		ENABLE_APT="yes"
-		;;
 	"--single")
 		# for backward compatibility
 		;;
@@ -57,8 +51,82 @@ while [ -n "$1" ]; do
 done
 }
 
+InstallProj() {
+	local ThisProj=$1
+	local logFile="${LogDir}/${ThisProj}.install"
+	[ -f "$logFile" ] && mv -f "$logFile" "${logFile}.old"
+
+	(
+		INFO "Start to install ${ThisProj}."
+		rm -rf "$TmpInstDir"/*
+		SetupProjInstallEnv $ThisProj
+
+		InstallProject $ThisProj && CreateTarball $ThisProj
+
+		INFO "Install $ThisProj finished!"
+
+	) &> >(tee $logFile)
+}
+
+ParallelInstallProjects() {
+	local projects=$@
+	local pickle="/tmp/$$.pickle"
+	local installProjs doneProjs
+
+	if [ -z "$projects" ]; then
+		echo "No projects input."
+		return 0
+	fi
+
+	echo "${ScriptsDir}/ProjectDepends.py --dump $pickle -p ${PLATFORM_ABBR} $projects"
+	${ScriptsDir}/ProjectDepends.py --dump $pickle -p "${PLATFORM_ABBR}" $projects
+	echo "${ScriptsDir}/ParallelProjects.py --init $pickle -x $projects"
+	${ScriptsDir}/ParallelProjects.py --init $pickle -x $projects
+
+	while true; do
+		installProjs=$(${ScriptsDir}/ParallelProjects.py --next -c "$ProcessCount" $doneProjs)
+		if [ "NULL" = "$installProjs" ]; then
+			echo "Done."
+			break
+		fi
+
+		for ThisProj in $installProjs; do
+			InstallProj $ThisProj >/dev/null &
+			echo "[Installing] $ThisProj"
+		done
+		wait
+
+		doneProjs=
+		for proj in $installProjs; do
+			doneProjs="$doneProjs $proj"
+			if CheckProjectStatus install $proj > /dev/null; then
+				echo "[Success] $proj"
+			else
+				echo "[Failed] $proj"
+			fi
+		done
+	done
+
+	${ScriptsDir}/ParallelProjects.py --purge
+	rm $pickle
+}
+
 main() {
 	local projectList=
+
+	if [ -z "$1" ]; then
+		Usage
+	fi
+
+	ARGS=$(getopt -u -l $DefaultLongArgs,single $DefaultArgs $@)
+
+	if [ $? -ne 0 ]; then
+		echo "You gave me option(s) that I do not know."
+		Usage
+		exit 1
+	fi
+	set -- $ARGS
+
 	local logFile=
 	local installFailed=N
 
@@ -67,23 +135,16 @@ main() {
 
 	SetupInstallEnv "$IsDebugBuild"
 
-	projectList=$(UnifyInstallProjects $InputProjs)
+	projectList=$(NormalizeInstallProjects $InputProjs)
 	INFO "projectList=\"$projectList\""
 
-	for ThisProj in $projectList; do
-		logFile="$LogDir/$ThisProj.install"
-		[ -f "$logFile" ] && mv -f $logFile ${logFile}.old
-
-	(
-		INFO "Start to install ${ThisProj}."
-		SetupProjInstallEnv $ThisProj
-
-		InstallProject $ThisProj && CreateTarball $ThisProj
-
-		INFO "Install $ThisProj finished!"
-
-	) &> >(tee $logFile)
-	done
+	if $Parallel && [ "$(wc -w <<< "$projectList")" -gt 1 ] ; then
+		ParallelInstallProjects $projectList
+	else
+		for ThisProj in $projectList; do
+			InstallProj "$ThisProj"
+		done
+	fi
 
 	if ! CheckErrorLog install $projectList; then
 		return 1;
diff --git a/include/check b/include/check
--- a/include/check
+++ b/include/check
@@ -1,24 +1,36 @@
 #!/bin/bash
-# Copyright (c) 2000-2016 Synology Inc. All rights reserved.
+# Copyright (c) 2000-2020 Synology Inc. All rights reserved.
 
 if [ -z "$__INCLUDE_CHECK__" ]; then
 __INCLUDE_CHECK__=defined
 
-Source include/init
-Source "include/config"
-Source "include/platforms"
-Source "include/errors"
+. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/init
 
-# Build system will select virtual build script first and then projName script in build.
+Source include/variable
+Source include/virtualProject
+Source include/config
+Source include/platforms
+
+
+GetProjectPath() {
+	local project="$1"
+
+	if [ "$(basename "$SynoBase")" = "ds.base" ]; then
+		echo "$SourceDir/$(GetVirtualProjectName "$(GetVirInstProjectName "$project")")"
+	else
+		echo "$SourceDir/$(GetVirInstProjectName "$project")"
+	fi
+}
+
 CheckScript() {
 	local projName="$1"
 	local type=$2
 	local findScript=
+	local virtualName=$(GetVirtualProjectExtension $projName)
+	local projPath="$(GetProjectPath "$projName")"
 
-	if [ -f "$SourceDir/$projName/$ConfDir/$type" ]; then
-		findScript="$SourceDir/$projName/$ConfDir/$type"
-	elif [ -f "$ScriptsDir/$type/$projName" ]; then
-		findScript="$ScriptsDir/$type/$projName"
+	if [ -f "$projPath/$ConfDir/$type$virtualName" ]; then
+		findScript="$projPath/$ConfDir/$type$virtualName"
 	fi
 
 	echo $findScript
@@ -29,24 +41,11 @@ FindScript() {
 	local projName=$1
 	local type=$2
 	local script=
-	local removeArchExt="-32"
-	# if default build 32bit, user will input project-virtual-64.
-	if [ "$DefaultBuild32Bit" = "yes" ]; then
-		removeArchExt="-64"
-	fi
 
-	script=$(CheckScript $projName $type)
-	if [ -z "$script" ]; then
-		# for project-virtual-junior-32
-		script=$(CheckScript ${projName//$removeArchExt/} $type)
-		if [ -z "$script" ]; then
-			# for project-virtual-32
-			script=$(CheckScript ${projName//-virtual$removeArchExt/} $type)
-		fi
-	fi
+	script="$(CheckScript "$projName" "$type")"
 
 	if [ -n "$script" ]; then
-		echo $script
+		echo "$script"
 		return 0
 	else
 		return 1
@@ -56,6 +55,11 @@ FindScript() {
 findBuildScript() {
 	local projName=$1
 	FindScript "$projName" "build"
+}
+
+findBuildFlagsScript() {
+	local projName=$1
+	FindScript "$projName" "buildflags"
 }
 
 findInstallDevScript() {
@@ -70,12 +74,17 @@ findInstallScript() {
 
 findDependConf() {
 	local projName="$1"
-	local conf=$(FindScript "$projName" "depends")
-	if [ -n "$conf" ]; then
-		echo "$conf"
-	else
-		echo "$ScriptsDir/$GlobalDependConf"
-	fi
+	FindScript "$projName" "depends"
+}
+
+FindConflictConf() {
+	local projName="$1"
+	FindScript "$projName" "conflict"
+}
+
+findErrorScript() {
+	local projName=$1
+	FindScript "$projName" "error"
 }
 
 CheckPermission()
@@ -107,15 +116,20 @@ CheckInList() {
 	return 1
 }
 
+CheckProjectStatus() {
+	$ScriptsDir/include/errors.py $1 $2
+}
+
 CheckErrorLog()
 {
 	local errors
 	local warns
 	local logFile
-	local warnCount
+	local warnCount blocked blockedList
 	local allProjCount=0
 	local errProjCount=0
 	local warnProjCount=0
+	local blockProjCount=0
 	local ret=
 	local logType=$1
 	shift
@@ -149,21 +163,25 @@ CheckErrorLog()
 			if [ "$1" = "build" ]; then
 				warnCount=`grep -s "warning:" $logFile | wc -l`
 				if [ 0 -ne $warnCount ]; then
-					printf "%-30s:\t%4d warning(s)\n" $proj $warnCount
+					printf "%-40s:\t%4d warning(s)\n" $proj $warnCount
 					warns="Y"
 					warnProjCount=$(( $warnProjCount + 1 ))
 				fi
 			fi
+			blocked="$(grep -s "^\[Blocked\]" $logFile)"
+			if [ -n "$blocked" ]; then
+				blockedList="$blockedList $proj"
+				blockProjCount=$(( $blockProjCount + 1 ))
+			fi
 		fi
 		allProjCount=$(( $allProjCount + 1 ))
 	done
+	[ -n "$blockedList" ] && echo -e "\nBlocked projects:$blockedList\n"
 	echo -n "$allProjCount projects, $errProjCount failed"
 	if [ "$1" = "build" ]; then
-		echo ", $warnProjCount have warnings."
-	else
-		echo "."
+		echo -n ", $warnProjCount have warnings"
 	fi
-
+	echo ", $blockProjCount blocked."
 	echo ""
 	if [ "$errors" = "Y" ]; then
 		ERROR "Check [${errorFile}] for fixing errors."
@@ -184,29 +202,36 @@ CheckErrorOut()
 }
 
 INFO(){
+	local std_dest
+	[ "$ShowDebug" = "yes" ] && std_dest=">&3"
+
 	if [ $# -lt 2 ]; then
-		echo -e "[INFO] $1"
+		eval echo -e "[INFO] $1" $std_dest
 	else
 		if [ -z "$1" ]; then
-			echo -e [INFO] $2
+			eval echo -e "[INFO] $2" "$std_dest"
 		else
-			echo -e [$1] $2
+			eval echo -e "[$1] $2" "$std_dest"
 		fi
 	fi
 }
 
 ERROR(){
 	if [ $# -lt 2 ]; then
-		echo -e "\n[Error] $1\n" >&2
+		echo -e "[Error] $1" >&2
 	else
 		if [ -z "$1" ]; then
-			echo -e [Error] $2 >&2
+			echo -e "[Error] $2" >&2
 		else
-			echo -e [$1] $2 >&2
+			echo -e "[$1] $2" >&2
 		fi
 	fi
 }
 
+WARNING()
+{
+	echo -e "\033[93m[WARNING] $1\033[0m" >&2
+}
 
 ShowTimeCost()
 {
@@ -225,7 +250,7 @@ ShowTimeCost()
 	DIFF_MIN=$(((${DIFF_INT}/60)%60))
 	DIFF_HOUR=$(((${DIFF_INT}/3600)%60))
 
-	printf "Time cost: %02d:%02d:%02d %s\n" ${DIFF_HOUR} ${DIFF_MIN} ${DIFF_SEC}    ${TAG_INTERNAL}
+	printf "Time cost: %02d:%02d:%02d %s\n" ${DIFF_HOUR} ${DIFF_MIN} ${DIFF_SEC} "${TAG_INTERNAL}"
 }
 
 CheckTimeCostLog()
@@ -244,11 +269,25 @@ CheckTimeCostLog()
 		if [ -r "$logFile" ]; then
 			#echo "file: ${logFile}"
 			result=`grep "Time cost:" $logFile`
-			echo $result
+			[ -n "$result" ] && echo "$result"
 		fi
 	done
 
 	echo ""
+}
+
+GetBaseDirs()
+{
+	# by default, the BASEDIR should be /synosrc or /synosrc.xxx
+	# get dir path of scripts for following inclusion of other scripts
+	CurDir=`pwd`
+	BASEDIR=`dirname $1`
+	BASEDIR=`dirname ${BASEDIR}`
+
+	#echo "file: $0"
+	#echo "CurDir: ${CurDir}"
+	#echo "ScriptDir: ${ScriptsDir}"
+	echo "BASEDIR: ${BASEDIR}"
 }
 
 # FIXME for test
@@ -274,8 +313,20 @@ _get_key_value()
 	echo "$val"
 }
 
+GetDSMCriticalUpdateNumber() {
+	_get_key_value "smallfixnumber" "$VERSION_FILE"
+}
+
 GetDSMBuildNumber() {
 	_get_key_value "buildnumber" "$VERSION_FILE"
+}
+
+GetDSMPacking() {
+	_get_key_value "packing" "$VERSION_FILE"
+}
+
+GetDSMPackingID() {
+	_get_key_value "packing_id" "$VERSION_FILE"
 }
 
 GetDSMMajorNumber()
@@ -288,9 +339,35 @@ GetDSMMinorNumber()
 	_get_key_value "minorversion" "$VERSION_FILE"
 }
 
+GetSmallFixNumber()
+{
+	_get_key_value "smallfixnumber" "$VERSION_FILE"
+}
+
+GetProductVersion()
+{
+	_get_key_value "productversion" "$VERSION_FILE"
+}
+
+GetBuildTime()
+{
+	_get_key_value "buildtime" "$VERSION_FILE"
+}
+
+GetBuildDate()
+{
+	_get_key_value "builddate" "$VERSION_FILE"
+}
+
 Is64BitProject() {
 	local Proj=$1
 	local ProjExt=
+
+	if [ "$DefaultBuild32Bit" = "yes" ]; then
+		ProjExt=`GetVirtualProjectExtension $Proj`
+		HasSubStr "$ProjExt" "64$"
+		return
+	fi
 
 	Is32BitProject $Proj && return 1
 	return 0
@@ -304,7 +381,8 @@ Is32BitProject() { #{{{
 		return 0
 	fi
 
-	return 1
+	ProjExt=`GetVirtualProjectExtension $Proj`
+	HasSubStr "$ProjExt" "32$"
 } #}}}
 
 getPlatformExcludeProjs() {
@@ -338,42 +416,20 @@ ExcludeList() {
 	return 0
 }
 
-GetBuildPhase() {
-	local _file=$1
-	local _phase=
-
-	[ -z "$_file" ] && _file=$VERSION_FILE
-
-	_phase="`grep buildphase $_file | cut -d'"' -f2`"
-
-	if [ -n "$_phase" ]; then
-		echo $_phase
-		return 0
-	else
-		return 1
-	fi
-}
-
-GetBuildStage() {
-	echo release
-	return 0
-}
-
 SetupDSMBuildNumber() {
-	unset DSM_BUILD_NUM DSM_SHLIB_MAJOR DSM_SHLIB_MAJOR
+	unset DSM_BUILD_NUM DSM_SHLIB_MAJOR DSM_SHLIB_MINOR SMALLFIX_NUM DSM_STAGE PRODUCT_VERSION PACKING PACKING_ID
 	local file=${1:-$VERSION_FILE}
-	local phase=`GetBuildPhase $file`
 
-	if [ -z "$DSM_STAGE" ]; then
-		# get global info
-		DSM_BUILD_NUM=$(GetDSMBuildNumber "$file")
-		DSM_SHLIB_MAJOR=$(GetDSMMajorNumber "$file")
-		DSM_SHLIB_MINOR=$(GetDSMMinorNumber "$file")
-		DSM_STAGE=$(GetBuildStage $file $phase)
-		if [ $? -ne 0 ]; then
-			ERROR "cannot get build stage"
-			exit 1
-		fi
+	DSM_BUILD_NUM=$(GetDSMBuildNumber "$file")
+	DSM_SHLIB_MAJOR=$(GetDSMMajorNumber "$file")
+	DSM_SHLIB_MINOR=$(GetDSMMinorNumber "$file")
+	SMALLFIX_NUM=$(GetSmallFixNumber "$file")
+	PRODUCT_VERSION=$(GetProductVersion "$file")
+	PACKING=$(GetDSMPacking "$file")
+	PACKING_ID=$(GetDSMPackingID "$file")
+	if [ $? -ne 0 ]; then
+		ERROR "cannot get build stage"
+		exit 1
 	fi
 
 	if [ -z "$DSM_BUILD_NUM" ]; then
@@ -383,7 +439,7 @@ SetupDSMBuildNumber() {
 	[ -z "$DSM_SHLIB_MAJOR" ] && DSM_SHLIB_MAJOR=0
 	[ -z "$DSM_SHLIB_MINOR" ] && DSM_SHLIB_MINOR=0
 
-	export DSM_BUILD_NUM DSM_SHLIB_MAJOR DSM_SHLIB_MINOR
+	export DSM_BUILD_NUM DSM_SHLIB_MAJOR DSM_SHLIB_MINOR SMALLFIX_NUM PRODUCT_VERSION PACKING PACKING_ID
 }
 
 fi
diff --git a/include/install b/include/install
--- a/include/install
+++ b/include/install
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (c) 2000-2016 Synology Inc. All rights reserved.
+# Copyright (c) 2000-2020 Synology Inc. All rights reserved.
 
 if [ -z "$__INCLUDE_INSTALL__" ]; then
 __INCLUDE_INSTALL__=defined
@@ -7,14 +7,18 @@ __INCLUDE_INSTALL__=defined
 Source include/config
 Source include/check
 Source include/platforms
+
+Source include/virtualProject
 Source include/applyEnv
 BUILD_TARGET=""
 
 PlatformOpts=`AllPlatformOptionsComma`
-DefaultLongArgs="${PlatformOpts}platform:,with-debug,help"
-DefaultArgs="dhp:"
+DefaultLongArgs="${PlatformOpts}platform:,with-debug,help,parallel:"
+DefaultArgs="dhp:T"
 IsDebugBuild="N"
 DebType="bin"
+Parallel=false
+ProcessCount=8
 
 ParseDefaultInstallArgs(){
 UnHandledOpt=
@@ -32,6 +36,11 @@ while [ -n $1 ]; do
 		"-d" | "--with-debug")
 			export NOSTRIP="NOSTRIP"
 			IsDebugBuild="Y"
+			;;
+		"--parallel")
+			Parallel=true
+			ProcessCount=$2
+			shift
 			;;
 		"--help" | "-h")
 			Usage
@@ -68,6 +77,41 @@ if [ -z "$BUILD_OPT" ]; then
 fi
 }
 
+_MVDIR() {
+	local SOURCE="$1"
+	local DEST="$2"
+
+	[ ! -d "$TmpInstDir/$SOURCE" ] && return
+
+	if [ -n "$(ls --almost-all "$TmpInstDir/$SOURCE")" ]; then
+		echo "Move files from $SOURCE to $DEST"
+		mkdir --parents "$TmpInstDir/$DEST"
+		mv --no-clobber "$TmpInstDir/$SOURCE"/* "$TmpInstDir/$DEST"
+		rmdir "$TmpInstDir/$SOURCE" || echo "Error"
+	fi
+}
+
+NormailizeTarballFHS() {
+	local proj=$1
+	NormailizeLIB ${proj}
+	NormailizeBIN ${proj}
+	NormailizeSBIN ${proj}
+}
+
+NormailizeLIB() {
+	_MVDIR "/usr/lib64" "/usr/lib"
+	_MVDIR "/lib64" "/usr/lib"
+	_MVDIR "/lib" "/usr/lib"
+}
+
+NormailizeBIN() {
+	_MVDIR "/bin" "/usr/bin"
+}
+
+NormailizeSBIN() {
+	_MVDIR "/sbin" "/usr/sbin"
+}
+
 SetupInstallEnv(){
 	local debugBuild=$1
 
@@ -83,28 +127,23 @@ SetupInstallEnv(){
 	[ -d "$DebPkgDir" ] || mkdir -p $DebPkgDir
 }
 
-UnifyInstallProjects() {
+NormalizeInstallProjects() {
 	local projectList=
 
 	for proj in $@; do
 		projectList="${projectList} `basename ${proj}`"
 	done
 
+	if ! projectList=$(${ScriptsDir}/ProjectDepends.py -p "${PLATFORM_ABBR}" ${projectList}) ; then
+		CheckErrorOut 1 "Failed to get dependency list !!"
+	fi
+
 	echo $projectList
-}
-
-ExcludeProjects() {
-	local projList=$@
-	local retProjs=
-
-	retProjs=$(ExcludeList "$projList" "$(getPlatformExcludeProjs)")
-	BuildMachineOnly || retProjs=$(ExcludeList "$retProjs" ".*-virtual-protection dsm-Protection")
-	echo $retProjs
 }
 
 InstallProject() {
 	local proj=$1
-	local baseProj="${proj}"
+	local baseProj="`GetVirInstProjectName ${proj}`"
 	local installScript=
 
 	cd $SourceDir/$baseProj
@@ -115,11 +154,21 @@ InstallProject() {
 	fi
 
 	INFO "Execute install script: $installScript"
-	(. $installScript)
+	(
+		. $installScript
+	)
 
 	CheckProjectStatus install $proj > /dev/null
 
 	return $?
+}
+
+
+SetupTmpInstDir() {
+	local proj=$1
+	TmpInstDir="/tmp/_install_${proj}"
+	rm -rf "$TmpInstDir"
+	mkdir -p "$TmpInstDir"
 }
 
 SetupProjInstallEnv() {
@@ -127,13 +176,20 @@ SetupProjInstallEnv() {
 
 	if Is64BitProject "${proj}"; then
 		INFO "ENV" "Using 64bit environment."
-		ApplyInstallEnv "64"
+		ApplyInstallEnv "64" "$proj"
 	else
 		INFO "ENV" "Using 32bit environment."
-		ApplyInstallEnv "32"
+		ApplyInstallEnv "32" "$proj"
 	fi
+}
 
-	rm -rf $TmpInstDir/*
+CheckTarballExist() {
+	local proj=$1
+	local tarball=${proj}.txz
+
+	if [ ! -f "$TarBallDir/$tarball" ] && CheckInList "$proj" "$PlatformAppList"; then
+		ERROR "No such file $TarBallDir/$tarball"
+	fi
 }
 
 CreateTarball() {
@@ -141,10 +197,9 @@ CreateTarball() {
 	local haveFile=`ls $TmpInstDir`
 
 	if [ ! -z "$haveFile" ]; then
-		echo ""
 		echo "Create ${proj}.txz ..."
-		( cd "$TmpInstDir"; XZ_OPT=-3 tar cJpvf "$TarBallDir/${proj}.txz" * )
-		echo "[Done]"
+		( cd "$TmpInstDir"; XZ_OPT=-3 tar cJpf "$TarBallDir/${proj}.txz" * )
+		echo "Done"
 	else
 		INFO "WARNING" "$TmpInstDir is empty!"
 	fi
@@ -156,8 +211,8 @@ InstallPreparePkgDir() # $1: Target Dir $2: Dir list
 	TargetDir="$1"
 	for dirmode in $2
 	do
-		DIR=`echo ${dirmode} | cut -f1 -d':'`	
-		MODE=`echo ${dirmode} | cut -f2 -d':' -s`	
+		DIR=`echo ${dirmode} | cut -f1 -d':'`
+		MODE=`echo ${dirmode} | cut -f2 -d':' -s`
 		if [ -n "${MODE}" ]; then
 			MODE_ARG="-m ${MODE}"
 		fi
@@ -199,55 +254,6 @@ InstallPkgFiles() # $1: Target Dir $2: Path $3: Default mode $4: FileList
 			${STRIP} -s --remove-section=.note --remove-section=.comment "$FileInst"
 		fi
 	done
-}
-
-InstallPrepareDir() # $1: Dir list
-{
-	InstallPreparePkgDir "$TmpInstDir" "$@"
-}
-
-InstallFiles() # $1: Path $2: Default mode $3: FileList
-{
-	InstallPkgFiles "$TmpInstDir" "$@"
-}
-
-DoInstall()
-{
-	InstallPrepareDir "${INSTALL_DIRS}"
-
-	InstallFiles $LibDir 755 "${INSTALL_LIB}"
-	InstallFiles "/bin" 755 "${INSTALL_BIN}"
-	InstallFiles "/sbin" 755 "${INSTALL_SBIN}"
-	InstallFiles "/usr/bin" 755 "${INSTALL_USR_BIN}"
-	InstallFiles "/usr/sbin" 755 "${INSTALL_USR_SBIN}"
-	InstallFiles "/usr/syno/bin" 755 "${INSTALL_SYNO_BIN}"
-	InstallFiles "/usr/syno/sbin" 755 "${INSTALL_SYNO_SBIN}"
-	InstallFiles "/usr/syno/etc/rc.d" 755 "${INSTALL_RCD}"
-	InstallFiles "/etc" 644 "${INSTALL_ETC}"
-	InstallFiles "/etc/pam.d/" 644 "${INSTALL_PAM}"
-	InstallFiles "/usr/syno/etc" 644 "${INSTALL_SYNO_ETC}"
-	InstallFiles "/usr/local/bin" 755 "${INSTALL_LOCAL_BIN}"
-	InstallFiles "/usr/local/sbin" 755 "${INSTALL_LOCAL_SBIN}"
-	InstallFiles "/usr/local/etc/rc.d" 755 "${INSTALL_LOCAL_RCD}"
-	InstallFiles "/usr/local/etc" 644 "${INSTALL_LOCAL_ETC}"
-}
-
-is_support_apparmor() {
-	SupportAppArmorPlatform
-}
-
-_create_empty_tgz() {
-	touch ${TarBallDir}/${ThisProj}.tar
-	gzip ${TarBallDir}/${ThisProj}.tar
-	mv ${TarBallDir}/${ThisProj}.tar.gz ${TarBallDir}/${ThisProj}.tgz
-}
-
-_create_empty_txz() {
-	tar cJf "$TarBallDir/${ThisProj}.txz" --files-from /dev/null
-}
-
-SkipThisProject() {
-	_create_empty_txz
 }
 
 fi
